services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy2
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./source/client/build:/usr/share/nginx/html

  server:
    build:
      context: ./source/servers
    container_name: express_server2
    restart: "on-failure"
    expose:
      - 8080
    volumes:
      - './source/servers:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
