services:
  backend:
    build: 
      args:
      - NODE_ENV=development
      context: servers
    command: npm run start-watch
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./servers/src:/server/src:ro
      - ./servers/package.json:/server/package.json
      - ./servers/package-lock.json:/server/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
  frontend:
    build:
      context: client
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/server/src
      - /server/node_modules
    networks:
      - public
    depends_on:
      - servers
networks:
  public:
  private:
volumes:
  back-notused: